// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for analyzing inquiry submissions using GenAI to extract insights.
 *
 * - analyzeInquiryData - A function that handles the inquiry analysis process.
 * - AnalyzeInquiryDataInput - The input type for the analyzeInquiryData function.
 * - AnalyzeInquiryDataOutput - The return type for the analyzeInquiryData function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeInquiryDataInputSchema = z.object({
  inquiryText: z.string().describe('The text content of the inquiry submitted by the user.'),
  userType: z.string().optional().describe('The type of user submitting the inquiry (e.g., buyer, sourcing manager).'),
  productInterest: z.string().optional().describe('The product category the user is interested in (e.g., Knitwear, Woven).'),
  companyDetails: z.string().optional().describe('Additional details about the user’s company, if provided.'),
});

export type AnalyzeInquiryDataInput = z.infer<typeof AnalyzeInquiryDataInputSchema>;

const AnalyzeInquiryDataOutputSchema = z.object({
  sentiment: z.string().describe('The overall sentiment of the inquiry (e.g., positive, negative, neutral).'),
  topicTrends: z.array(z.string()).describe('Identified topic trends within the inquiry.'),
  potentialIssues: z.array(z.string()).describe('Any potential issues or urgent requests identified in the inquiry.'),
  overallSummary: z.string().describe('A summary of the inquiry including key topics, sentiment, and any identified issues.'),
});

export type AnalyzeInquiryDataOutput = z.infer<typeof AnalyzeInquiryDataOutputSchema>;

export async function analyzeInquiryData(input: AnalyzeInquiryDataInput): Promise<AnalyzeInquiryDataOutput> {
  return analyzeInquiryDataFlow(input);
}

const analyzeInquiryDataPrompt = ai.definePrompt({
  name: 'analyzeInquiryDataPrompt',
  input: {schema: AnalyzeInquiryDataInputSchema},
  output: {schema: AnalyzeInquiryDataOutputSchema},
  prompt: `You are an AI assistant designed to analyze inquiry submissions from a contact form for an apparel buying house.

  Your goal is to provide insights into the overall sentiment, topic trends, and any potential issues or urgent requests within the inquiries. This analysis will help prioritize and efficiently respond to inquiries.

  Analyze the following inquiry:

  Inquiry Text: {{{inquiryText}}}
  User Type: {{{userType}}}
  Product Interest: {{{productInterest}}}
  Company Details: {{{companyDetails}}}

  Provide the following outputs:

  - sentiment: The overall sentiment of the inquiry (e.g., positive, negative, neutral).
  - topicTrends: Identified topic trends within the inquiry.
  - potentialIssues: Any potential issues or urgent requests identified in the inquiry.
  - overallSummary: A summary of the inquiry including key topics, sentiment, and any identified issues.

  Format your response as a JSON object matching the following schema:
  ${AnalyzeInquiryDataOutputSchema.description}
  `,
});

const analyzeInquiryDataFlow = ai.defineFlow(
  {
    name: 'analyzeInquiryDataFlow',
    inputSchema: AnalyzeInquiryDataInputSchema,
    outputSchema: AnalyzeInquiryDataOutputSchema,
  },
  async input => {
    const {output} = await analyzeInquiryDataPrompt(input);
    return output!;
  }
);
