// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for analyzing inquiries submitted through a contact form using an LLM.
 *
 * - analyzeInquiry - A function that handles the inquiry analysis process.
 * - AnalyzeInquiryInput - The input type for the analyzeInquiry function.
 * - AnalyzeInquiryOutput - The return type for the analyzeInquiry function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeInquiryInputSchema = z.object({
  inquiryText: z.string().describe('The text content of the inquiry submitted by the user.'),
  userType: z.string().optional().describe('The type of user submitting the inquiry (e.g., buyer, sourcing manager).'),
  productInterest: z.string().optional().describe('The product category the user is interested in (e.g., Knitwear, Woven).'),
  companyDetails: z.string().optional().describe('Additional details about the user’s company, if provided.'),
});

export type AnalyzeInquiryInput = z.infer<typeof AnalyzeInquiryInputSchema>;

const AnalyzeInquiryOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the inquiry.'),
  keyTopics: z.array(z.string()).describe('A list of key topics or themes identified in the inquiry.'),
  priorityScore: z.number().describe('A numerical score indicating the priority of the lead (e.g., 1-10).'),
  suggestedAction: z.string().describe('A suggested action to take based on the inquiry analysis (e.g., follow up, request more information).'),
});

export type AnalyzeInquiryOutput = z.infer<typeof AnalyzeInquiryOutputSchema>;

export async function analyzeInquiry(input: AnalyzeInquiryInput): Promise<AnalyzeInquiryOutput> {
  return analyzeInquiryFlow(input);
}

const analyzeInquiryPrompt = ai.definePrompt({
  name: 'analyzeInquiryPrompt',
  input: {schema: AnalyzeInquiryInputSchema},
  output: {schema: AnalyzeInquiryOutputSchema},
  prompt: `You are an AI assistant designed to analyze customer inquiries for an apparel buying house.

  Your goal is to extract key information, identify trends, and prioritize leads to help the company respond effectively.

  Analyze the following inquiry:

  Inquiry Text: {{{inquiryText}}}
  User Type: {{{userType}}}
  Product Interest: {{{productInterest}}}
  Company Details: {{{companyDetails}}}

  Provide the following outputs:

  - summary: A concise summary of the inquiry.
  - keyTopics: A list of key topics or themes identified in the inquiry.
  - priorityScore: A numerical score indicating the priority of the lead (1-10, higher is better).
  - suggestedAction: A suggested action to take based on the inquiry analysis (e.g., follow up, request more information).

  Format your response as a JSON object matching the following schema:
  ${AnalyzeInquiryOutputSchema.description}
  `,
});

const analyzeInquiryFlow = ai.defineFlow(
  {
    name: 'analyzeInquiryFlow',
    inputSchema: AnalyzeInquiryInputSchema,
    outputSchema: AnalyzeInquiryOutputSchema,
  },
  async input => {
    const {output} = await analyzeInquiryPrompt(input);
    return output!;
  }
);
