
// This is an autogenerated file from Firebase Studio.
import {NextRequest, NextResponse} from 'next/server';
import {getAuth} from 'firebase-admin/auth';
import {app} from '@/lib/firebase/server-config';

export async function POST(request: NextRequest) {
  const {idToken} = await request.json();

  if (!idToken) {
    return NextResponse.json({error: 'No ID token provided.'}, {status: 400});
  }

  const expiresIn = 60 * 60 * 24 * 5 * 1000; // 5 days

  try {
    const sessionCookie = await getAuth(app).createSessionCookie(idToken, {expiresIn});
    const options = {
      name: 'session',
      value: sessionCookie,
      maxAge: expiresIn,
      httpOnly: true,
      secure: true,
    };
    const response = NextResponse.json({status: 'success'}, {status: 200});
    response.cookies.set(options);
    return response;
  } catch (error) {
    console.error('Error creating session cookie:', error);
    return NextResponse.json({error: 'Failed to create session'}, {status: 401});
  }
}

export async function DELETE() {
  const response = NextResponse.json({status: 'success'}, {status: 200});
  response.cookies.set({
    name: 'session',
    value: '',
    expires: new Date(0),
  });
  return response;
}
