
// This is an autogenerated file from Firebase Studio.
import {NextRequest, NextResponse} from 'next/server';
import { getApps, initializeApp, getApp, App } from 'firebase-admin/app';
import {getAuth as getAdminAuth} from 'firebase-admin/auth';
import { firebaseConfig } from '@/firebase/config';

// This file is the single source of truth for the server-side Firebase Admin App.
// It ensures that the app is initialized only once.
const appName = 'firebase-admin-app-route';
let app: App;
if (!getApps().find(a => a.name === appName)) {
  app = initializeApp({
    projectId: firebaseConfig.projectId,
  }, appName);
} else {
  app = getApp(appName);
}

export async function POST(request: NextRequest) {
  const {idToken} = await request.json();

  if (!idToken) {
    return NextResponse.json({error: 'No ID token provided.'}, {status: 400});
  }

  const expiresIn = 60 * 60 * 24 * 5 * 1000; // 5 days

  try {
    const sessionCookie = await getAdminAuth(app).createSessionCookie(idToken, {expiresIn});
    const options = {
      name: 'session',
      value: sessionCookie,
      maxAge: expiresIn,
      httpOnly: true,
      secure: true,
    };
    const response = NextResponse.json({status: 'success'}, {status: 200});
    response.cookies.set(options);
    return response;
  } catch (error) {
    console.error('Error creating session cookie:', error);
    return NextResponse.json({error: 'Failed to create session'}, {status: 401});
  }
}

export async function DELETE(request: NextRequest) {
  const response = NextResponse.json({status: 'success'}, {status: 200});
  const sessionCookieName = 'session';
  const cookie = request.cookies.get(sessionCookieName);

  if (cookie) {
    try {
      const decodedClaims = await getAdminAuth(app).verifySessionCookie(cookie.value, true);
      await getAdminAuth(app).revokeRefreshTokens(decodedClaims.sub);
    } catch(error) {
      console.error("Error revoking refresh tokens:", error);
    }
  }

  response.cookies.set({
    name: sessionCookieName,
    value: '',
    expires: new Date(0),
  });

  return response;
}
