// This is an autogenerated file from Firebase Studio.
import {initializeApp, getApps, getApp} from 'firebase/app';
import {getAuth} from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyA0uKuwTfKVwNnyPyv_ul1fnU9XiqBjBo8",
  authDomain: "studio-2779115415-2fdb9.firebaseapp.com",
  projectId: "studio-2779115415-2fdb9",
  storageBucket: "studio-2779115415-2fdb9.appspot.com",
  messagingSenderId: "604004472088",
  appId: "1:604004472088:web:23ea2297f305ab31047a6d"
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth = getAuth(app);

export {app, auth};
