
// This is an autogenerated file from Firebase Studio.
import {getApps, initializeApp, cert, getApp} from 'firebase-admin/app';

const app = getApps().length
  ? getApp()
  : initializeApp();

export {app};
