// This is an autogenerated file from Firebase Studio.
import { getApps, initializeApp, getApp, App } from 'firebase-admin/app';

// This ensures we initialize the app only once.
const appName = 'firebase-admin-app-e7b3c2';

const app = getApps().find(a => a.name === appName) || initializeApp(undefined, appName);

export { app };
